branches:
  only:
  - master
  - eXXcellent_adaptions
language: java
# for an overview see https://docs.travis-ci.com/user/reference/overview/
os:
  - linux
dist: bionic
jdk:
#  - oraclejdk8
#  - oraclejdk9
  - openjdk8
cache:
  directories:
    - $HOME/.m2/repository
# 'true' will skip install step
install: true

# define the stage ordering for job building
stages:
  - name: build_with_hibernate
  - name: build_with_eclipselink + coverage upload
  - name: deploy
    if: branch = eXXcellent_adaptions

# define the jobs self for all the stages
jobs:
  include:
    - stage: build_with_hibernate
      script: mvn clean verify -Duse-hibernate -DskipITs -Dmaven.source.skip -Dmaven.javadoc.skip
    - stage: build_with_eclipselink + coverage upload
      script: mvn clean verify -Duse-eclipselink -Ddisable.jetty=false -Dmaven.source.skip -Dmaven.javadoc.skip
      after_success: 
        bash <(curl -s https://codecov.io/bash) -X gcov -Z -F unittests -f code-coverage-report/target/jacoco-aggregate-ut/jacoco.xml
    - stage: deploy
      script: "cp .travis.settings.xml $HOME/.m2/settings.xml && sh -c 'mvn clean package deploy:deploy -DskipTests -Djetty.skip'"


