branches:
  only:
  - master
  - eXXcellent_adaptions
  - fix/TestJPAQueryWhereClauseFailsOnTravis
language: java
# for an overview see https://docs.travis-ci.com/user/reference/overview/
os:
  - linux
sudo: required
dist: xenial
jdk:
#  - oraclejdk8
#  - oraclejdk9
  - openjdk8
cache:
  directories:
    - $HOME/.m2/repository
# 'true' will skip install step
install: true
stages:
#  - build_with_hibernate
  - build_with_eclipselink
#  - deploy
jobs:
  include:
#    - stage: build_with_hibernate
#      script: mvn clean verify -Duse-hibernate -DskipITs -Dmaven.source.skip -Dmaven.javadoc.skip
    - stage: build_with_eclipselink
      script: mvn clean verify -Duse-eclipselink -Ddisable.jetty=false -Dmaven.source.skip -Dmaven.javadoc.skip
#    - stage: deploy
#      provider: script
#      script: "cp .travis.settings.xml $HOME/.m2/settings.xml && sh -c 'mvn clean package deploy:deploy -DskipTests -Djetty.skip'"
#      skip_cleanup: false
#      on:
#        branch: eXXcellent_adaptions


