package org.apache.olingo.jpa.metadata.core.edm.mapper.impl;

public interface TextConstants {
  public static final String NEWLINE = "\n";
  public final static String HEADER_TEXT =
      "/**" + NEWLINE
      + " * This ugly code was generated by OData-JPA-Adapter client-api-code-generator. Do not edit!" + NEWLINE
      + " **/";
}
