name: Build OData-JPA-Adapter
on:
  push:
    branches:
      - eXXcellent_adaptions
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  
jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        java-version: [ 11, 8 ]
        jpa-provider: ["eclipselink", "hibernate"]
    name: Build with Java ${{ matrix.java-version }} and ${{ matrix.jpa-provider }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode clean verify -Duse-${{ matrix.jpa-provider }} -Ddisable.jetty=false -Dmaven.source.skip -Dmaven.javadoc.skip
